version: '3.5'
services:
  ms:
    build:
      context: .
    command: bash -c "alembic upgrade head && python -u -B main.py"
    image: python-api-image:latest
    container_name: python-api-image
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    networks:
      - api-python
    depends_on:
      - "db"
  db:
    image: postgres:12-alpine
    container_name: feira-livre-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=api-db
      - POSTGRES_DB=feira-livre
    volumes:
      - api-db:/var/lib/postgresql
    restart: always
    networks:
      - api-python

volumes:
  api-db:
    driver: local

networks:
  api-python:
    name: api-python-network
